name: Daily SEO Publishing

on:
  schedule:
    - cron: "7 0 * * *"
    - cron: "55 0 * * *"
    - cron: "43 1 * * *"
    - cron: "31 2 * * *"
    - cron: "19 3 * * *"
    - cron: "7 4 * * *"
    - cron: "55 4 * * *"
    - cron: "43 5 * * *"
    - cron: "31 6 * * *"
    - cron: "19 7 * * *"
    - cron: "7 8 * * *"
    - cron: "55 8 * * *"
    - cron: "43 9 * * *"
    - cron: "31 10 * * *"
    - cron: "19 11 * * *"
    - cron: "7 12 * * *"
    - cron: "55 12 * * *"
    - cron: "43 13 * * *"
    - cron: "31 14 * * *"
    - cron: "19 15 * * *"
    - cron: "7 16 * * *"
    - cron: "55 16 * * *"
    - cron: "43 17 * * *"
    - cron: "31 18 * * *"
    - cron: "19 19 * * *"
    - cron: "7 20 * * *"
    - cron: "55 20 * * *"
    - cron: "43 21 * * *"
    - cron: "31 22 * * *"
    - cron: "19 23 * * *"

